<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MyDevPlatform.Domain/MyDevPlatform.Domain.csproj" />
    <ProjectReference Include="../MyDevPlatform.Contracts/MyDevPlatform.Contracts.csproj" />
  </ItemGroup>
</Project>
